disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  - vertical_whitespace
  - shorthand_operator
  - large_tuple
  - class_delegate_protocol
  - control_statement
  
opt_in_rules:
  - empty_string

cyclomatic_complexity:
  warning: 20
  error: 40
  
line_length: 250
  
function_body_length:
  warning: 30
  error: 500

file_length:
  warning: 500
  error: 1200
  
type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
  excluded:
    - id
    - URL
    - MainViewController
    
trailing_semicolon: error
closing_brace: error
opening_brace: error
return_arrow_whitespace: error
statement_position: error
syntactic_sugar: error
vertical_parameter_alignment: error
redundant_void_return: error
redundant_optional_initialization: error
opening_brace: warning
implicit_getter: error
comma: error
colon: error
weak_delegate: error
force_try: warning
force_cast: warning
todo: warning
mark: warning
