disabled_rules:
  - control_statement

opt_in_rules:
  - empty_string

cyclomatic_complexity:
  warning: 25
  error: 50

line_length: 250

file_length:
  warning: 500
  error: 1200
  
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
    
function_body_length:
  warning: 120
  error: 300
    
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
  excluded:
    - id
    - URL
    - MainViewController
