name: Spacecraft
options:
  bundleIdPrefix: "com.cassiodiego.Spacecraft"
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
targets:
  Spacecraft:
    type: application
    platform: iOS
    info:
      path: Spacecraft/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UIRequiredDeviceCapabilities: [armv7]
        UIRequiresFullScreen: true
        UIStatusBarHidden: true
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    deploymentTarget: 12.0
    sources:
      - path: Spacecraft
    dependencies:
      - sdk: GameKit.framework
