on: [push, pull_request]
name: ios-spacecraft-game
jobs:
  build:
    name: Spacecraft
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Device List
        run: xcrun instruments -s devices   
      - name: Build
        run: xcodebuild clean test -project Spacecraft.xcodeproj -scheme "Spacecraft" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

