on:
    pull_request:
        branches:
            - master
name: spacecraft-ios
jobs:
  build:
    name: Spacecraft
    runs-on: macOS-latest
    steps:
      - name: Installing Xcodegen
        run: git clone https://github.com/cassiodiego/xcodegen.git && cd XcodeGen && make install
      - name: Checkout
        uses: actions/checkout@master
      - name: Gererating xcodeproj
        run: xcodegen generate  
      - name: Build
        run: xcodebuild clean -project Spacecraft.xcodeproj -scheme "Spacecraft" -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest"

