on:
    pull_request:
        branches:
            - master
name: spacecraft-ios
jobs:
  build:
    name: Spacecraft
    runs-on: macOS-latest
    steps:
      - name: Build
        run: xcodebuild clean -project Spacecraft.xcodeproj -scheme "Spacecraft" -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest"

