
on: [push, pull_request]
name: Spacecraft
jobs:
  build:
    name: Spacecraft
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: xcodebuild clean test -project Spacecraft.xcodeproj -scheme "Spacecraft" -destination "name=iPhone X,OS=12.4"

